# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       coreutils

# >> macros
# << macros

# >> bcond_with
# << bcond_with

# >> bcond_without
# << bcond_without

Summary:    The GNU core utilities: a set of tools commonly used in shell scripts
Version:    8.23
Release:    3
Epoch:      1
Group:      System/Base
License:    GPLv3+
URL:        http://www.gnu.org/software/coreutils/
Source0:    %{name}-%{version}.tar.xz
Source100:  coreutils.yaml
BuildRequires:  automake
BuildRequires:  gmp-devel
BuildRequires:  libacl-devel
BuildRequires:  libattr-devel
BuildRequires:  libcap-devel
BuildRequires:  gettext-devel
BuildRequires:  perl
BuildRequires:  xz
BuildRequires:  pam-devel
Provides:   mktemp
Provides:   fileutils = %{version}-%{release}
Provides:   sh-utils = %{version}-%{release}
Provides:   stat = %{version}-%{release}
Provides:   textutils = %{version}-%{release}
Conflicts:   glibc < 2.2
Conflicts:   tetex < 1.0.7-66
Conflicts:   util-linux < 2.22.2
Obsoletes:   fileutils <= 4.1.9
Obsoletes:   sh-utils <= 2.0.12
Obsoletes:   stat <= 3.3
Obsoletes:   textutils <= 2.0.21

%description
These are the GNU core utilities.  This package is the combination of
the old GNU fileutils, sh-utils, and textutils packages.


%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
AUTOPOINT=true autoreconf -fi
# << build pre

%configure --disable-static \
    --libexecdir=%{_libdir} \
    --enable-no-install-program=groups,hostname,kill,uptime

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post

# let be compatible with old fileutils, sh-utils and textutils packages :
mkdir -p $RPM_BUILD_ROOT{/bin,%_bindir,%_sbindir,/sbin}
for f in basename cat chgrp chmod chown cp cut date dd df echo env false link ln ls mkdir mknod mktemp mv nice pwd rm rmdir sleep sort stty sync touch true uname unlink
do
mv $RPM_BUILD_ROOT{%_bindir,/bin}/$f
done

# chroot was in /usr/sbin :
mv $RPM_BUILD_ROOT{%_bindir,%_sbindir}/chroot
# {cat,sort,cut} were previously moved from bin to /usr/bin and linked into
for i in env cut; do ln -sf ../../bin/$i $RPM_BUILD_ROOT/usr/bin; done

# (sb) Deal with Installed (but unpackaged) file(s) found
rm -f $RPM_BUILD_ROOT%{_infodir}/dir

%find_lang %name

%lang_package

%docs_package

# << install post

%files
%defattr(-,root,root,-)
%doc COPYING NEWS README THANKS
%{_bindir}/*
/bin/*
%{_sbindir}/chroot
%{_libdir}/%{name}
%doc %{_infodir}/coreutils.info*.gz
%doc %{_mandir}/man1/*.1.gz
%dir %{_datadir}/locale/*/LC_TIME
# >> files
# << files
